title: Cornell Physics Wiki
email: cornellphysicssociety@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Student-run wiki for students interested in physics at Cornell University
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://Cornell-SPS.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed
